FROM python:3.9-slim-buster
RUN mkdir /bot /bot/logs /bot/counts
COPY asd_bot_multigroup.py /bot
COPY motivational_replies.py /bot
COPY requirements.txt /bot
WORKDIR /bot
RUN pip3 install -r requirements.txt
# requirements generated by: pip3 install python-telegram-bot==11.1.0 matplotlib
ENV COUNTS_DIR="/bot/counts/"
ENV GROUP_DB="group_db.txt"
ENV DB_FILE="_past_asd.txt"
ENV CNT_FILE="_current_count.txt"
ENV GRAPH_FILE="_history_graph.png"
CMD ["python", "-u", "asd_bot_multigroup.py", ">", "logs/log_$(date +%s).txt", "2>&1"]

# build with
#   docker build -t asdbot .
# run with
# -e TOKEN=... -e CST_CID=...