FROM python:3.9-slim-buster

RUN mkdir -p /bot/counts
COPY requirements.txt /bot
WORKDIR /bot
# install requirements as soon as possible so rebuilds are faster
RUN pip3 install -r requirements.txt
# requirements generated by: pip3 install python-telegram-bot==11.1.0 matplotlib
COPY asd_bot_multigroup.py ./
COPY motivational_replies.py ./

ENV COUNTS_DIR="/bot/counts/"
ENV GROUP_DB="group_db.txt"
ENV DB_FILE="_past_asd.txt"
ENV CNT_FILE="_current_count.txt"
ENV GRAPH_FILE="_history_graph.png"

CMD ["python", "-u", "asd_bot_multigroup.py"]

# build with
#   docker build -t asdbot .
# run with
# -e TOKEN=... -e CST_CID=...
