FROM python:3.9-slim-buster
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y --no-install-recommends tzdata \
    && rm -rf /var/lib/apt/lists/*
RUN ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata
RUN mkdir /bot /bot/logs /bot/counts
COPY requirements.txt /bot
WORKDIR /bot
# install requirements as soon as possible so rebuilds are faster
RUN pip3 install -r requirements.txt
# requirements generated by: pip3 install python-telegram-bot==11.1.0 matplotlib
COPY asd_bot_multigroup.py /bot
COPY motivational_replies.py /bot
ENV COUNTS_DIR="/bot/counts/"
ENV GROUP_DB="group_db.txt"
ENV DB_FILE="_past_asd.txt"
ENV CNT_FILE="_current_count.txt"
ENV GRAPH_FILE="_history_graph.png"
CMD ["python", "-u", "asd_bot_multigroup.py", ">", "logs/log_$(date +%s).txt", "2>&1"]

# build with
#   docker build -t asdbot .
# run with
# -e TOKEN=... -e CST_CID=...
